name: indexed_set
version: 1.0.0+2
description: >
  IndexedSet is a Set implementation that computes an index for each of its
  elements and exposes this mapping through the [] operator.
author: Philipp Schiffmann <philippschiffmann93@gmail.com>
homepage: https://github.com/pschiffmann/indexed-set.dart
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  collection: ^1.4.0
  built_collection: ^4.0.0
  meta: ^1.1.0
  quiver: ^2.0.0
dev_dependencies:
  test: ^1.0.0
