name: indexed_set
description: Provides an IndexedSet class, an implementation of Set that computes an index for each of its elements, and exposes this mapping through the [] operator.
author: Philipp Schiffmann <philippschiffmann93@gmail.com>
homepage: https://github.com/pschiffmann/indexed-set.dart
dependencies:
  collection: ^1.4.0
  built_collection: ^2.1.3
  quiver: ^0.25.0
dev_dependencies:
  test: any
